declare module '*.gif'
declare module '*.jpg'
declare module '*.jpeg'
declare module '*.png'
declare module '*.svg'

declare module 'store'
declare module 'moveto'
declare module 'react-animate-on-change'
declare module 'react-spring'
