const STATUS_NONE = 'NONE'
const STATUS_LOADING = 'LOADING'
const STATUS_LOADED = 'LOADED'
const STATUS_FAILED = 'FAILED'

export const fetchStatusTypes = {
    NONE: STATUS_NONE,
    LOADING: STATUS_LOADING,
    LOADED: STATUS_LOADED,
    FAILED: STATUS_FAILED
}
